# Site settings
title: Whatsup Mailbox 
email: info@whatsupmailbox.com
description: Whatsup mailbox!
# baseurl: "/" # the subpath of your site, e.g. /blog/
# url: "http://sodakscreens.github.io" # the base hostname & protocol for your site
twitter_username: whatsupmailbox
github_username:  

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"